name: Your New Jekyll Site
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "news/page:num"
baseurl: ""
plugins: [jekyll-paginate]
repository: 'mkelly505/frs.git'
future: true
github: [metadata]

# Build Settings
port: 4000